### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'create_connection'

### ISSUE THREAD

**Issue by sorter** [jleclanche/django-push-notifications#420]
Hello,

I've been using django-push-notifications without issue for some time now without configuration change. Recently upgraded libraries and now I'm getting this error without any configuration change.

```
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/tmp/djangodev/local/lib/python2.7/site-packages/push_notifications/models.py", line 159, in send_message
    **kwargs
  File "/tmp/djangodev/local/lib/python2.7/site-packages/push_notifications/apns.py", line 113, in apns_send_message
    certfile=certfile, **kwargs
  File "/tmp/djangodev/local/lib/python2.7/site-packages/push_notifications/apns.py", line 66, in _apns_send
    client = _apns_create_socket(certfile=certfile, application_id=application_id)
  File "/tmp/djangodev/local/lib/python2.7/site-packages/push_notifications/apns.py", line 38, in _apns_create_socket
    use_alternative_port=get_manager().get_apns_use_alternative_port(application_id)
  File "/tmp/djangodev/local/lib/python2.7/site-packages/apns2/client.py", line 41, in __init__
    self._init_connection(use_sandbox, use_alternative_port, proto)
  File "/tmp/djangodev/local/lib/python2.7/site-packages/apns2/client.py", line 50, in _init_connection
    self._connection = self.__credentials.create_connection(server, port, proto)
```

Has anyone else run into this issue?

**Comment by Kiirojin** [comment]
Confirmed running into same issue. Happens on 1.5.0 and not 1.4.1.

**Comment by jamaalscarlett** [comment]
@matthewh @kit-cat I see a lot of apns related issues related to 1.5.0.  Has there been some upgrade to apns2 that has broken functionality in this package?

**Comment by Kiirojin** [comment]
This is just because the APNsClient call on apns2 doesn't support unicode strings for whatever reason. Calling .encode('utf-8') the string passed into the APNsClient call fixes the issue.

**Comment by carn1x** [comment]
Confirmed, fixed by forcefully sending a bytestring for the certificath path `b'/path/to/file.pem'`

**Comment by mhsiddiqui** [comment]
I am getting this error in 1.6 version. Is it not fixed yet?

**Comment by matthewh** [comment]
@mhsiddiqui No changes have to made to the codebase for this issue. Did you try the workarounds suggested by @Kiirojin or @carn1x?

**Comment by mhsiddiqui** [comment]
I converted my apns token path to string in my settings.py file (which was unicode before this) and the error then I got is "APNSServerError: BadDeviceToken". I think this is expected behaviour. I was not getting this error when token has expired in 1.4.1 version. I think I had to put a try catch statement now.
