### ISSUE TITLE
GCM device id displayed as integer in admin

### ISSUE THREAD

**Issue by borjafp** [jleclanche/django-push-notifications#68]
When edit a GCM device record the id value is displayed as integer but the field require hex value to validate the form. 

You have to convert the integer value in hex manually before save the record.

**Comment by jleclanche** [comment]
Is this still an issue for everyone on the latest versions of django and uuidfield?

**Comment by borjafp** [comment]
Yes, tested on django 1.7.4 and uuidfield 0.5.0.

**Comment by jleclanche** [comment]
Would be great to test on 1.8 with the changes I just pushed.

**Comment by jleclanche** [comment]
Version 1.2.1 is out, please try it in there.

**Comment by jamaalscarlett** [comment]
Still exists in latest build.
See https://github.com/jleclanche/django-push-notifications/pull/163

**Comment by jleclanche** [comment]
This is fixed in 1.3
